services:
  - type: web
    name: foodnest-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn api.server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
